import Hero from "@components/sections/Hero";
import Colors from "@components/ui/Colors";
import { } from "next/font/local";

export const metadata = {
  title: "Fleetwood | About",
  description: "Generated by create next app",
}

export default function Home() {

  return (
    <div>
      <Hero title="Hi">
        <h3>I&apos;m <span className="font-bold">Fleetwood</span></h3>
        <h4>I am a leader.</h4>
        <h4>I am an engineer.</h4>
        <h4>I am a solver.</h4>
      </Hero>

      <Colors />
    </div>
  );
}
