import MainNav from "@components/nav/MainNav";
import ParallaxBg from "@components/ParallaxBg";
import { ThemeProvider } from "@components/providers/ThemeProvider";
import Footer from "@components/sections/Footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

interface LayoutProps {
  children: React.ReactNode;
  nav?: boolean;
  footer?: boolean;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, nav = true, footer = true }: LayoutProps) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={twMerge(inter.className)}>
        <div className="relative h-screen w-screen overflow-hidden">
      <ParallaxBg className="absolute inset-0 z-0" />
      <div className="relative flex flex-col h-full max-w-5xl px-8 mx-auto overflow-hidden z-10">
        {nav && <MainNav className="flex-shrink-0 sticky top-0" />}
        <main className="flex-grow overflow-y-auto my-2">
          {children}
        </main>
        {footer && <Footer className="flex-shrink-0 sticky bottom-0" />}
      </div>
    </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
