import Hero from "@components/sections/Hero";
import Colors from "@components/ui/Colors";
import Content from "@components/sections/Content";
import { addArticle } from "@lib/linguistics";
import { } from "next/font/local";
import MainNav from "@fleetwood/components/nav/MainNav";
import Image from "next/image";
import ImgHero from "@fleetwood/components/sections/ImgHero";

export const metadata = {
  title: "Fleetwood | Hi!",
  description: "Generated by create next app",
};

export default function Home() {
  const roles = [
    "leader",
    "engineer",
    "solver",
    "collaborator",
    "mentor",
    "ally",
  ];

  return (
    <div className="relative flex flex-col max-h-full max-w-5xl px-8 mx-auto overflow-hidden z-10">
    <MainNav className="flex-shrink-0 sticky top-0" />
    <main className="flex-grow overflow-y-auto my-2">
      <ImgHero title="Hi" img={{src: "/img/me-1.jpg", alt: "me", width: 740, height: 960}}>
        <div className="flex w-full justify-stretch">
          <div>
            <h3>
              I&apos;m <span className="font-bold">Fleetwood</span>
            </h3>
            <h4>
              I am {addArticle(roles[Math.floor(Math.random() * roles.length)])}.
            </h4>
          </div>
        </div>
      </ImgHero>

      <Colors />
    </main>
    </div>
  );
}
