import Hero from "@components/sections/Hero";
import Colors from "@components/ui/Colors";
import { addArticle } from "@lib/linguistics";
import { } from "next/font/local";
import RootLayout from "./layout";

export const metadata = {
  title: "Fleetwood | Hi!",
  description: "Generated by create next app",
}

export default function Home() {
  const roles = ["leader", "engineer", "solver", "collaborator", "mentor", "ally"]

  return (
    <RootLayout footer={false}>
      <div>
        <Hero title="Hi">
          <h3>I&apos;m <span className="font-bold">Fleetwood</span></h3>
          <h4>I am {addArticle(roles[Math.floor(Math.random() * roles.length)])}.</h4>
        </Hero>

        <Colors />  
      </div>
    </RootLayout>
  );
}
