import Hero from "@components/sections/Hero";
import Timeline from "@components/sections/Timeline";
import Milestone from "@components/sections/timeline/Milestone";
import {} from "next/font/local";

export const metadata = {
  title: "Fleetwood | Resume",
  description: "Generated by create next app",
}

export default function ResumePage() {
  const albums = [
    {
      artist: "Bruce Springsteen",
      title: "Born in the U.S.A.",
      content:
        "Born in the U.S.A. is the seventh studio album by the American singer-songwriter Bruce Springsteen, released on June 4, 1984, by Columbia Records.",
    },
    {
      artist: "Van Halen",
      title: "1984",
      content:
        "1984 is the sixth studio album by American rock band Van Halen, released on January 9, 1984. It was the last Van Halen studio album until A Different Kind of Truth to feature lead singer David Lee Roth, who left the band in 1985 following creative differences.",
    },
    {
      artist: "Metallica",
      title: "Ride the Lightning",
      content:
        "Ride the Lightning is the second studio album by the American heavy metal band Metallica, released on July 27, 1984, by the independent record label Megaforce Records. The album was recorded in three weeks with producer Flemming Rasmussen.",
    },
    {
      artist: "Prince",
      title: "Purple Rain",
      content:
        "Purple Rain is the sixth studio album by the American singer, songwriter, producer, and multi-instrumentalist Prince. It was released on June 25, 1984, by Warner Bros. Records as the soundtrack album to the 1984 film of the same name.",
    },
    {
      artist: "Madonna",
      title: "Like A Virgin",
      content:
        "Like a Virgin is the second studio album by American singer Madonna, released on November 12, 1984, by Sire Records. Following the success of her 1983 self-titled debut album, Madonna was eager to start working on its follow-up.",
    },
    {
      artist: "The Cars",
      title: "Heartbeat City",
      content:
        'Heartbeat City is the fifth studio album by American new wave band the Cars, released on March 13, 1984, by Elektra Records. This marks the band\'s first album not produced by long-time producer Roy Thomas Baker, instead opting to produce with Robert John "Mutt" Lange.',
    },
    {
      artist: "U2",
      title: "The Unforgettable Fire",
      content:
        "The Unforgettable Fire is the fourth studio album by Irish rock band U2. It was produced by Brian Eno and Daniel Lanois, and released on 1 October 1984 by Island Records. The band wanted to pursue a new musical direction following the harder-hitting rock of their previous album, War.",
    },
    {
      artist: "Bryan Adams",
      title: "Reckless",
      content:
        "Reckless is the fourth studio album by Canadian singer-songwriter Bryan Adams, released by A&M Records on November 5, 1984 to coincide with Adams' 25th birthday. Like its predecessor Cuts Like a Knife, the album was entirely produced by Adams and Bob Clearmountain.",
    },
    {
      artist: "Footloose",
      title: "Musical Soundtrack",
      content:
        "Footloose is the original soundtrack of the Paramount motion picture Footloose. The original nine-track album was released in 1984 and reached number one on the US Billboard 200 chart on April 21, 1984, where it stayed until June 30, 1984.",
    },
    {
      artist: "The Smiths",
      title: "Hatful of Hollow",
      content:
        "Hatful of Hollow is a compilation album by English rock band the Smiths, released on 12 November 1984 by Rough Trade Records. The album features BBC Radio 1 studio recordings and two contemporary singles, including their epitomic track How Soon Is Now?.",
    },
  ];
  return (
    <div>
      <Hero title="History">
        Oh, the places I&apos;ve been!
      </Hero>
      <Timeline vertical>
        {albums.map((album, index) => (
          <Milestone
            key={index}
            title={album.artist}
            first={index === 0}
            last={index === albums.length - 1}
          >
            <div>
              <div className="font-bold">{album.title}</div>
              <div>{album.content}</div>
            </div>
          </Milestone>
        ))}
      </Timeline>

    </div>
  );
}
