import Hero from "@components/sections/Hero";
import Timeline from "@components/sections/Timeline";
import Milestone from "@components/sections/timeline/Milestone";
import Markdown from "@fleetwood/components/sections/Markdown";
import { Iceberg } from "next/font/google";
import {} from "next/font/local";
import { IconBase } from "react-icons/lib";

export const metadata = {
  subject: "Fleetwood | Resume",
  description: "Generated by create next app",
};

export default function ResumePage() {
  const places = [
    {
      title: "LGE US, (Zenith)",
      icon: "LGE.png",
      tenure: "12/2022 - present",
      role: "Senior Engineering Manager",
      content: "Senior Engineering Manager",
    },
    {
      title: "Peloton",
      icon: "peloton.png",
      tenure: "08/2019 - 09/2022",
      role: "Engineering Manager",
      content: `
### Led 5 cross-functional, full-stack engineering teams (3-11 engineers)
 - Logistics, Member Support,
 -  Greenfield: Overflow, Personalization, Product Marketing
● Fostered a culture of learning, respect, transparency, and trust
 ○ Motivated, coached, and mentored software engineers
 ○ Peer-coaching fellow engineering managers
 ○ Recruiting, onboarding, performance reviews, career advancement, training
 ○ Facilitated team meetings, 1:1’s and other forums to support group and individual development objectives
● Drove technical initiatives
 ○ Clean, robust, maintainable, and performant systems
 ○ Improve processes and collaboration within- and cross-team
 ○ Identified cross-functional dependencies and blockers across engineering, design, and product management
● Short and long-term technical strategies
 ○ Epic/Sprint, Quarterly and Annual roadmapping
 ○ Collaboration with Product, Design, Program Management and UX
 ○ KPIs to measure team effectiveness through key metrics (e.g. DORA)
● Worked closely with technical program managers to ensure the successful delivery of projects
 ○ Respectfully challenge ideas, call out potential trade-offs
● Led various working and program groups
 ○ Microsite (SPA), Onboarding, Incident Management
 ○ Defining program goals and milestones
 ○ Socializing, evangelizing and implementing org standards, processes and best practices`,
    },
    {
      title: "Active Campaign",
      icon: "activeCampaign.png",
      tenure: "07/2018 - 05/2019",
      role: "Engineering Manager",
      content: "Engineering Manager",
    },
    {
      title: "Conversant",
      icon: "conversant.png",
      tenure: "05/2015 - 03/2018",
      role: "Engineering Manager",
      content: "Engineering Manager",
    },
    {
      title: "AbelsonTaylor",
      icon: "abelsonTaylor.png",
      tenure: "10/2010 - 02/2015",
      role: "Engineering Manager",
      content: "Engineering Manager",
    },
    {
      title: "b|Media",
      tenure: "2005 - 2008",
      role: "New Media Developer",
      content: "Engineering Manager",
    },
    {
      title: "IBM",
      tenure: "2002 - 2005",
      role: "Lead Intranet Developer",
      content: "Engineering Manager",
    },
    {
      title: "Arthur Andersen",
      tenure: "2000 - 2002",
      role: "Shredding Stuff",
      content: "lol jk, I was the Help Desk Lead",
    },
  ];

  const albums = [
    {
      title: "Bruce Springsteen",
      subject: "Born in the U.S.A.",
      content:
        "Born in the U.S.A. is the seventh studio album by the American singer-songwriter Bruce Springsteen, released on June 4, 1984, by Columbia Records.",
    },
    {
      title: "Van Halen",
      subject: "1984",
      content:
        "1984 is the sixth studio album by American rock band Van Halen, released on January 9, 1984. It was the last Van Halen studio album until A Different Kind of Truth to feature lead singer David Lee Roth, who left the band in 1985 following creative differences.",
    },
    {
      title: "Metallica",
      subject: "Ride the Lightning",
      content:
        "Ride the Lightning is the second studio album by the American heavy metal band Metallica, released on July 27, 1984, by the independent record label Megaforce Records. The album was recorded in three weeks with producer Flemming Rasmussen.",
    },
    {
      title: "Prince",
      subject: "Purple Rain",
      content:
        "Purple Rain is the sixth studio album by the American singer, songwriter, producer, and multi-instrumentalist Prince. It was released on June 25, 1984, by Warner Bros. Records as the soundtrack album to the 1984 film of the same name.",
    },
    {
      title: "Madonna",
      subject: "Like A Virgin",
      content:
        "Like a Virgin is the second studio album by American singer Madonna, released on November 12, 1984, by Sire Records. Following the success of her 1983 self-subjectd debut album, Madonna was eager to start working on its follow-up.",
    },
    {
      title: "The Cars",
      subject: "Heartbeat City",
      content:
        'Heartbeat City is the fifth studio album by American new wave band the Cars, released on March 13, 1984, by Elektra Records. This marks the band\'s first album not produced by long-time producer Roy Thomas Baker, instead opting to produce with Robert John "Mutt" Lange.',
    },
    {
      title: "U2",
      subject: "The Unforgettable Fire",
      content:
        "The Unforgettable Fire is the fourth studio album by Irish rock band U2. It was produced by Brian Eno and Daniel Lanois, and released on 1 October 1984 by Island Records. The band wanted to pursue a new musical direction following the harder-hitting rock of their previous album, War.",
    },
    {
      title: "Bryan Adams",
      subject: "Reckless",
      content:
        "Reckless is the fourth studio album by Canadian singer-songwriter Bryan Adams, released by A&M Records on November 5, 1984 to coincide with Adams' 25th birthday. Like its predecessor Cuts Like a Knife, the album was entirely produced by Adams and Bob Clearmountain.",
    },
    {
      title: "Footloose",
      subject: "Musical Soundtrack",
      content:
        "Footloose is the original soundtrack of the Paramount motion picture Footloose. The original nine-track album was released in 1984 and reached number one on the US Billboard 200 chart on April 21, 1984, where it stayed until June 30, 1984.",
    },
    {
      title: "The Smiths",
      subject: "Hatful of Hollow",
      content:
        "Hatful of Hollow is a compilation album by English rock band the Smiths, released on 12 November 1984 by Rough Trade Records. The album features BBC Radio 1 studio recordings and two contemporary singles, including their epitomic track How Soon Is Now?.",
    },
  ];
  return (
    <div className="bg-glass rounded-xl p-10 min-h-screen">
      <h2 className="text-secondary dark:text-primary">History</h2>
      <div className="bg-black/50 text-white p-4 my-10 text-lg font-serif rounded-lg text-center">
        <div className="italic">Oh, the places I&apos;ve been!</div>
        <div>- Dr. Suess (kinda)</div>
      </div>
      <Timeline>
        {places.map((item, index) => (
          <Milestone
            key={index}
            icon={item.icon}
            title={item.title}
            first={index === 0}
            last={index === places.length - 1}
            className="min-w-full"
          >
            <div className="">{item.tenure}</div>
            <div className="text-xl font-semibold text-primary">{item.role}</div>
            <div className="divider divider-base-100"></div>
            <Markdown>{item.content}</Markdown>
          </Milestone>
        ))}
      </Timeline>
    </div>
  );
}
